### ISSUE TITLE
Invalid codepoints behavior was updated

### ISSUE THREAD

**Issue by Altai-man** [p6-css/CSS-Grammar-p6#8]
Hi! Thanks for your awesome module.

I am looking at its tests and since https://github.com/MoarVM/MoarVM/commit/15e94eecb30b850497e847c09d6b31130b775bdc an assumption in tests about parsing `0x123456` isn't hold true:
```
> 0x123456 > 0x10FFFF
True
```
which results in
```
===> Testing: CSS::Grammar:ver<0.3.4>:auth<github:p6-css>
[CSS::Grammar] t/compat.t ............. ok
[CSS::Grammar] # Failed test 'css3 escape no warnings'
[CSS::Grammar] # at /mnt/Blin/data/zef-data/store/CSS-Grammar-p6.git/8d3f7e2c0692b04c0cfb989acf0db5f26d20c384/lib/CSS/Grammar/Test.pm (CSS::Grammar::Test) line 76
[CSS::Grammar] # expected: ''
[CSS::Grammar] #      got: 'invalid unicode code-point: U+123456'
[CSS::Grammar] # You failed 1 test of 125
[CSS::Grammar] t/css3-syntax.t ........ 
[CSS::Grammar] Dubious, test returned 1 (wstat 256, 0x100)
[CSS::Grammar] Failed 1/125 subtests 
[CSS::Grammar] t/error-handling.t ..... ok
[CSS::Grammar] t/parse-stylesheets.t .. ok
[CSS::Grammar] t/parse-warnings.t ..... ok
[CSS::Grammar] t/regex-tokens.t ....... ok
[CSS::Grammar] Test Summary Report
[CSS::Grammar] -------------------
```

So it seems a broken codepoint now produces an error message instead of silencing it. Can tests be updated to avoid this assumption (preferably without breaking backward compatibility, of course) or to make something more clever to unblock installation?

**Comment by dwarring** [comment]
Thanks @Altai-man. That was unintentional. Have changedto a valid codepoint.
